### PR TITLE
Forwards compatible fs search.

### PR DESCRIPTION
**Pull request by oliver-sanders**
These changes partially address #xxxx
These changes close #xxxx
This is a small change with no associated Issue.

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

### CODE REVIEW

**Comment by datamel** [comment]
Thanks for adding these debugs - I'm still a bit clueless! I can see an isodatetime error in one. The rest seem to have problems as there is no json to decode? I guess cylc scan not returning anything?

**Comment by oliver-sanders** [comment]
> I guess cylc scan not returning anything?

Looks like it, but why?! Will have to put some more advanced debug in.

**Comment by oliver-sanders** [comment]
https://travis-ci.org/github/oliver-sanders/cylc/jobs/668869683#L807

These lines show that `cylc scan` is exiting with error codes 1 and 2

**Comment by oliver-sanders** [comment]
So, taking a quick look at the code (which I should have done to start with), the lines which extract the cylc version are within the `try` block. This shields them from quite a broad range of exceptions including `ValueError` and `TypeError` which means that if these exceptions occur they are silently ignored (which may be what we are seeing).

I've moved the lines into the `else` branch of the `try` so they aren't covered by this, we might see traceback.

**Comment by datamel** [comment]
> So, taking a quick look at the code (which I should have done to start with), the lines which extract the cylc version are within the try block. This shields them from quite a broad range of exceptions including ValueError and TypeError which means that if these exceptions occur they are silently ignored (which may be what we are seeing).
> I've moved the lines into the else branch of the try so they aren't covered by this, we might see traceback.

Ah thanks!

**Comment by oliver-sanders** [comment]
And there it is:

https://travis-ci.org/github/oliver-sanders/cylc/jobs/669328100#L704

The version parsing needs to be able to handle non-integer version components (e.g. Cylc 8.0a1).

For Python3 we have the wonderful `packaging.version` which handles all of this for us (including version comparison), in Python2 you are left to figure it out yourself.

**Comment by datamel** [comment]
Ah that is so funny. I looked into using that first and decided to go with just stripping my own down. I will fix it tomorrow. Thanks so much for your help!

**Pull request closed without merging**
